#!/usr/bin/env python3
"""Package utilitaires NobaraForgeKDE."""

from schemas import (
    ExternalPackage,
    ExternalPackageList,
    FlatpakApp,
    FlatpakList,
    Package,
    PackageList,
    Theme,
    ThemeList,
)

from .file_utils import (
    ConfigError,
    ConfigManager,
    ensure_directory,
    find_file_in_paths,
    get_user_home,
    load_json,
    load_package_list,
    safe_read_file,
    safe_write_file,
    save_json,
)
from .logging_utils import (
    Colors,
    Logger,
    debug,
    error,
    header,
    info,
    log_debug,
    log_error,
    log_header,
    log_info,
    log_step,
    log_success,
    log_warn,
    set_log_file,
    step,
    success,
    warn,
)
from .state_manager import (
    ACTION_DNF_INSTALL,
    ACTION_DNF_REMOVE,
    ACTION_EXTERNAL_INSTALL,
    ACTION_FLATPAK_INSTALL,
    StateEntry,
    StateError,
    StateManager,
    get_state_manager,
)
from .subprocess_utils import (
    CommandResult,
    check_command_exists,
    check_flatpak_installed,
    check_package_installed,
    dnf_install,
    dnf_remove,
    dnf_update,
    dnf_upgrade,
    flatpak_install,
    flatpak_list,
    git_clone,
    run_bash_script,
    run_command,
    run_python_script,
    run_sudo_command,
    system_update,
    timeshift_available,
    timeshift_create_snapshot,
)
from .validation import (
    ConfigValidationError,
    validate_all_configs,
    validate_config,
    validate_external_config,
    validate_flatpak_config,
    validate_install_config,
    validate_remove_config,
    validate_theme_config,
)
